### ISSUE TITLE
ちぃうごのセリフが変わらない

### ISSUE THREAD

**Issue by NXVZBGBFBEN** [naotiki/chiiugo#1]
## バグについての説明
+ ちぃうごのセリフが変わりません．
+ IDEを起動したタイミングでセリフは変わります．
+ 最低でも5分以上セリフが変わらないことを確認しています．

## 期待されていた動作
+ セリフが変わる

## バグを再現するために
1. ちぃうごクライアントアプリを起動する
2. IDEを起動する
(1の時点で動作は再現されます)

## 環境
<table>
<tr>
<td>OS</td>
<td>Windows 11 Pro 22H2 Build 22621.1702</td>
</tr>
<tr>
<td>クライアントアプリ</td>
<td>Release v0.0.1-dev4 (<code>Chiiugo-0.0.1.msi</code>)</td>
</tr>
<tr>
<td>IDE</td>
<td>IntelliJ IDEA 2023.1.2 (Ultimate Edition) Build #IU-231.9011.34</td>
</tr>
<tr>
<td>IDEプラグイン</td>
<td>1.0-SNAPSHOT3</td>
</tr>
</table>

**Comment by naotiki** [comment]
次のバージョンで修正される予定です。

**Comment by NXVZBGBFBEN** [comment]
対応感謝します
