### ISSUE TITLE
Bug: 起動失敗させると二度と起動しなくなる

### ISSUE THREAD

**Issue by toreis-up** [naotiki/chiiugo#2]
# What's happens?

クライアントアプリが起動できない（Failed to launch JVMと出る）

# How to reproduce

1. `ChiiugoConf.json`の`spawnCount`を10000とかにする（起動失敗するレベルまで上げる）
2. 起動に失敗させる（Failed to launch JVMがでる）
3. 1.での変更をもとに戻す
4. 起動しない ← 今回報告したいのはここ

# Environment

- Windows 11 Pro（winver 22621.1702）
- https://github.com/naotiki/chiiugo/releases/tag/v0.0.1-alpha4

# Additional info

入れ直すと動きます

**Comment by naotiki** [comment]
こちら側で再現ができませんでした。
Failed to launchの原因としては、
- ChiiugoConf.jsonの形式が誤っている
- ちぃうごを２つ以上同時に起動しようとしている。(タスクマネージャーなどで確認してみてください)
- GPUに起因するバグにより起動できない。(AMD系でよく見られます。[naotiki/chiiugo/docs/troubleshooting.md](https://github.com/naotiki/chiiugo/blob/main/docs/troubleshooting.md))

などが挙げられます。
`v0.0.1-alpha4`以降のバージョンでは`C:\Users\<User>\AppData\Local\Chiiugo`ディレクトリで
```powershell
java.exe -cp "app/client-app-0.0.1-alpha4-9182fb228f1056774f3c34486da13a0.jar;app/;app/*" chiiugo.app.MainKt
```
を実行することでちぃうごの標準出力を見ることが可能です。
お手数ですが、出力された情報を教えてくださると原因究明がしやすくなります。
ご迷惑をおかけしますが、よろしくお願いします。

**Comment by toreis-up** [comment]
自分の環境でも再現しなくなりました…

おそらくですが、

1. コンフィグ変えて起動させようとする（メモリをとりあえず食う）
2. メモリを食うだけ食ったが足りないので起動しない
3. 起動しないと思った私がもう一回起動させようとする
4. エラー吐く

というケースだと思います…

何にせよ、ご迷惑おかけしました…
